// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;
using backend.Models.Orders;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425050900_AddOrderManagementSchema")]
    partial class AddOrderManagementSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "address_type", new[] { "BILLING", "SHIPPING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", new[] { "CANCELLED", "CONFIRMED", "CREATED", "DELIVERED", "SHIPPED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "CARD", "COD", "PREPAID", "UPI" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "FAILED", "PAID", "PENDING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_txn_status", new[] { "FAILED", "INITIATED", "SUCCESS" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Orders.CustomerPrescription", b =>
                {
                    b.Property<string>("CustomerPrescriptionsId")
                        .HasColumnType("varchar")
                        .HasColumnName("customer_prescriptions_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<decimal?>("LeftAdd")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("left_add");

                    b.Property<int?>("LeftAxis")
                        .HasColumnType("integer")
                        .HasColumnName("left_axis");

                    b.Property<decimal?>("LeftCylinder")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("left_cylinder");

                    b.Property<decimal?>("LeftSphere")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("left_sphere");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PD")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pd");

                    b.Property<decimal?>("RightAdd")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("right_add");

                    b.Property<int?>("RightAxis")
                        .HasColumnType("integer")
                        .HasColumnName("right_axis");

                    b.Property<decimal?>("RightCylinder")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("right_cylinder");

                    b.Property<decimal?>("RightSphere")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("right_sphere");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CustomerPrescriptionsId");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("customer_prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_customer_prescriptions_left_axis_range", "left_axis IS NULL OR (left_axis >= 0 AND left_axis <= 180)");

                            t.HasCheckConstraint("CK_customer_prescriptions_pd_non_negative", "pd IS NULL OR pd >= 0");

                            t.HasCheckConstraint("CK_customer_prescriptions_right_axis_range", "right_axis IS NULL OR (right_axis >= 0 AND right_axis <= 180)");
                        });
                });

            modelBuilder.Entity("backend.Models.Orders.Order", b =>
                {
                    b.Property<string>("OrdersId")
                        .HasColumnType("varchar")
                        .HasColumnName("orders_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<OrderStatus>("OrderStatus")
                        .HasColumnType("order_status")
                        .HasColumnName("order_status");

                    b.Property<PaymentStatus>("PaymentStatus")
                        .HasColumnType("payment_status")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("OrdersId");

                    b.HasIndex("CustomerOrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_total_amount_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.Orders.OrderAddress", b =>
                {
                    b.Property<string>("OrderAddressesId")
                        .HasColumnType("varchar")
                        .HasColumnName("order_addresses_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("line2");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<AddressType>("Type")
                        .HasColumnType("address_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrderAddressesId");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("order_addresses");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderItem", b =>
                {
                    b.Property<string>("OrderItemsId")
                        .HasColumnType("varchar")
                        .HasColumnName("order_items_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrderItemsId");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_items_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("CK_order_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_order_items_total_price_non_negative", "total_price >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.Orders.OrderItemCustomization", b =>
                {
                    b.Property<string>("OrderItemCustomizationsId")
                        .HasColumnType("varchar")
                        .HasColumnName("order_item_customizations_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CustomizationOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("customization_option_id");

                    b.Property<int?>("CustomizationValueId")
                        .HasColumnType("integer")
                        .HasColumnName("customization_value_id");

                    b.Property<string>("OrderItemId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("order_item_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("OrderItemCustomizationsId");

                    b.HasIndex("CustomizationOptionId");

                    b.HasIndex("CustomizationValueId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("order_item_customizations");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderStatusLog", b =>
                {
                    b.Property<string>("OrderStatusLogsId")
                        .HasColumnType("varchar")
                        .HasColumnName("order_status_logs_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<OrderStatus>("Status")
                        .HasColumnType("order_status")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrderStatusLogsId");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("order_status_logs");
                });

            modelBuilder.Entity("backend.Models.Orders.Payment", b =>
                {
                    b.Property<string>("PaymentsId")
                        .HasColumnType("varchar")
                        .HasColumnName("payments_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_order_id");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method")
                        .HasColumnName("method");

                    b.Property<PaymentTxnStatus>("Status")
                        .HasColumnType("payment_txn_status")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PaymentsId");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationImage", b =>
                {
                    b.Property<int>("CustomizationImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomizationOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomizationValueId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("CustomizationImageId");

                    b.HasIndex("CustomizationOptionId");

                    b.HasIndex("CustomizationValueId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomizationImages");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationOption", b =>
                {
                    b.Property<int>("CustomizationOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationOptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("CustomizationOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomizationOptions");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationValue", b =>
                {
                    b.Property<int>("CustomizationValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationValueId"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomizationOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CustomizationValueId");

                    b.HasIndex("CustomizationOptionId");

                    b.ToTable("CustomizationValues");
                });

            modelBuilder.Entity("backend.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasPrescription")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("backend.Models.Products.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Orders.CustomerPrescription", b =>
                {
                    b.HasOne("backend.Models.Orders.Order", "Order")
                        .WithMany("CustomerPrescriptions")
                        .HasForeignKey("CustomerOrderId")
                        .HasPrincipalKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Orders.Order", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderAddress", b =>
                {
                    b.HasOne("backend.Models.Orders.Order", "Order")
                        .WithMany("OrderAddresses")
                        .HasForeignKey("CustomerOrderId")
                        .HasPrincipalKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("backend.Models.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("CustomerOrderId")
                        .HasPrincipalKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderItemCustomization", b =>
                {
                    b.HasOne("backend.Models.Products.CustomizationOption", "CustomizationOption")
                        .WithMany()
                        .HasForeignKey("CustomizationOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Products.CustomizationValue", "CustomizationValue")
                        .WithMany()
                        .HasForeignKey("CustomizationValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Orders.OrderItem", "OrderItem")
                        .WithMany("Customizations")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizationOption");

                    b.Navigation("CustomizationValue");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderStatusLog", b =>
                {
                    b.HasOne("backend.Models.Orders.Order", "Order")
                        .WithMany("OrderStatusLogs")
                        .HasForeignKey("CustomerOrderId")
                        .HasPrincipalKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.Models.Orders.Payment", b =>
                {
                    b.HasOne("backend.Models.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerOrderId")
                        .HasPrincipalKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationImage", b =>
                {
                    b.HasOne("backend.Models.Products.CustomizationOption", "CustomizationOption")
                        .WithMany()
                        .HasForeignKey("CustomizationOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Products.CustomizationValue", "CustomizationValue")
                        .WithMany()
                        .HasForeignKey("CustomizationValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Products.Product", "Product")
                        .WithMany("CustomizationImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizationOption");

                    b.Navigation("CustomizationValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationOption", b =>
                {
                    b.HasOne("backend.Models.Products.Product", "Product")
                        .WithMany("CustomizationOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationValue", b =>
                {
                    b.HasOne("backend.Models.Products.CustomizationOption", "CustomizationOption")
                        .WithMany("CustomizationValues")
                        .HasForeignKey("CustomizationOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizationOption");
                });

            modelBuilder.Entity("backend.Models.Products.ProductImage", b =>
                {
                    b.HasOne("backend.Models.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Orders.Order", b =>
                {
                    b.Navigation("CustomerPrescriptions");

                    b.Navigation("OrderAddresses");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderStatusLogs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.Orders.OrderItem", b =>
                {
                    b.Navigation("Customizations");
                });

            modelBuilder.Entity("backend.Models.Products.CustomizationOption", b =>
                {
                    b.Navigation("CustomizationValues");
                });

            modelBuilder.Entity("backend.Models.Products.Product", b =>
                {
                    b.Navigation("CustomizationImages");

                    b.Navigation("CustomizationOptions");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
